version: 0.2

env:
  variables:
    NPM_CONFIG_PRODUCTION: "false"

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Instalando dependencias (incluyendo devDependencies)…"
      - npm install

  build:
    commands:
      - echo "Corriendo vite build…"
      - npm run build

  post_build:
    commands:
      - echo "Sincronizando dist/ a S3…"
      - aws s3 sync dist/ s3://finnancy-artefacts-bucket --delete

artifacts:
  files:
    - '**/*'
