version: 0.2

env:
  variables:
    NPM_CONFIG_PRODUCTION: "false"

phases:
  install:
    commands:
      - cd ..
      - echo "Instalando dependencias…"
      - npm install

  build:
    commands:
      - cd ..
      - echo "Construyendo…"
      - npm run build

  post_build:
    commands:
      - cd ..
      - echo "Desplegando…"
      - aws s3 sync build/ s3://finnancy-artefacts-bucket --delete

artifacts:
  files:
    - '**/*'
