version: 0.2

env:
  variables:
    NODE_ENV: "production"
    NPM_CONFIG_PRODUCTION: "false"

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm ci --include=dev

  build:
    commands:
      - echo "Building React application..."
      - npm run build
      - echo "Build completed successfully"

artifacts:
  files:
    - "**/*"