version: 0.2

env:
  variables:
    NPM_CONFIG_PRODUCTION: "false"

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "🚀 Install phase: installing all deps…"
      - npm install

  build:
    commands:
      - echo "🔨 Build phase: running vite build…"
      - npm run build

  post_build:
    commands:
      - echo "☁️ Post-build: deploying 'dist/' to S3…"
      - aws s3 sync dist/ s3://finnancy-artefacts-bucket --delete

artifacts:
  base-directory: dist
  files:
    - '**/*'
